### ISSUE TITLE
Use ConfigMap for Cloud Controller

### ISSUE THREAD

**Issue by bsctl** [clastix/cluster-api-kamaji-vsphere#19]
Use Config Map for Cloud Controller Configuration:

```yaml
data:
  vsphere.conf: |
    # Global properties...
    global:
      port: 443
      {{- if $config.thumbprint }}
      thumbprint: {{ $config.thumbprint }}
      {{- else if $config.caFile }}
      ca-file: {{ $config.caFile }}
      {{- else }}
      insecureFlag: true
      {{- end }}
      secretName: {{ $config.secret.name }}
      secretNamespace: {{ .Release.Namespace }}

    vcenter:
      {{ $config.vcenter }}:
        server: {{ $config.vcenter }}
        datacenters:
          - {{ $config.datacenter }}

    labels:
      region: {{ $config.region }}
      zone: {{ $config.zone }}
```
